### ISSUE TITLE
In the Woods

### ISSUE THREAD

**Issue by ugghhhaley** [Bulbacode/fucking-famished#18] opened 2021-01-26 08:18 UTC
I live in a city. I set the radius to 50 miles. It gave me a total of 5 restaurants and then said there was no more and that I live in the woods. I LIVE IN A WHOLE CITY SIR.

**Comment by Bulbacode** [comment] 2021-01-26 11:42
Closing as duplicate of #14

**Closed by Bulbacode** 2021-01-26 11:42 UTC
Labels: duplicate
